// Generated by rpc4next-cli. Do not edit manually.

import type { ProcedureRouteContract } from "rpc4next/server";

export type Params = {};
export type RouteContract = ProcedureRouteContract<"/feed", Params>;

export const routeContract = {
  pathname: "/feed",
  params: {} as Params,
} as RouteContract;