app:
  - changed-files:
      - any-glob-to-any-file: "src/**"

ci:
  - changed-files:
      - any-glob-to-any-file: ".github/**"

cli:
  - changed-files:
      - any-glob-to-any-file: "src/cli/**"
      - any-glob-to-any-file: "cli/**"

docs:
  - changed-files:
      - any-glob-to-any-file: "docs/**"
      - any-glob-to-any-file: "**/*.md"
  - title: ["^docs?:"]

test:
  - changed-files:
      - any-glob-to-any-file: "tests/**"
      - any-glob-to-any-file: "**/*.test.*"
  - title: ["^test:"]

feature:
  - head-branch: ["^feature/", "^feat/"]
  - title: ["^feat:"]

fix:
  - head-branch: ["^bugfix/", "^fix/", "^bug/"]
  - title: ["^fix:"]

chore:
  - title: ["^chore:"]

refactor:
  - title: ["^refactor:"]

release:
  - head-branch: ["^release/"]

hotfix:
  - head-branch: ["^hotfix/"]
