// Generated by rpc4next-cli. Do not edit manually.

import type { ProcedureRouteContract } from "rpc4next/server";

export type Params = {};
export type RouteContract = ProcedureRouteContract<"/api/client-bundle-leak-sentinel", Params>;

export const routeContract = {
  pathname: "/api/client-bundle-leak-sentinel",
  params: {} as Params,
} as RouteContract;