// Generated by rpc4next-cli. Do not edit manually.

import type { ProcedureRouteContract } from "rpc4next/server";

export type Params = {};
export type RouteContract = ProcedureRouteContract<"/response-unwrap", Params>;

export const routeContract = {
  pathname: "/response-unwrap",
  params: {} as Params,
} as RouteContract;