import {
  NEWLINE,
  RPC4NEXT_GENERATED_SCHEMA_VERSION,
  RPC4NEXT_CLIENT_IMPORT_PATH,
  STATEMENT_TERMINATOR,
  TYPE_KEYS,
  TYPE_RPC_GENERATED_PATH_STRUCTURE,
} from "./constants.js";
import { scanAppDir } from "./route-scanner.js";
import { createImport, createStringLiteral } from "./type-utils.js";

export const ROUTE_CONTRACT_GENERATED_MARKER =
  "// Generated by rpc4next-cli. Do not edit manually.";

export const generatePathStructure = (outputPath: string, baseDir: string) => {
  const { pathStructure, imports, paramsTypes } = scanAppDir(outputPath, baseDir);
  const pathStructureType = `export type PathStructure = ${TYPE_RPC_GENERATED_PATH_STRUCTURE}<${pathStructure}, ${RPC4NEXT_GENERATED_SCHEMA_VERSION}>${STATEMENT_TERMINATOR}`;

  const importsStr = imports.length
    ? `${imports
        .sort((a, b) => a.path.localeCompare(b.path, undefined, { numeric: true }))
        .map((v) => v.statement)
        .join(NEWLINE)}`
    : "";

  const keyTypes = [
    TYPE_RPC_GENERATED_PATH_STRUCTURE,
    ...TYPE_KEYS.filter((type) => pathStructure.includes(type)),
  ];
  const keyTypesImportStr = createImport(keyTypes.join(" ,"), RPC4NEXT_CLIENT_IMPORT_PATH);
  const dirParamsTypes = paramsTypes.map(({ paramsType, dirPath, pathname }) => {
    const params = [
      ROUTE_CONTRACT_GENERATED_MARKER,
      "",
      'import type { ProcedureRouteContract } from "rpc4next/server";',
      "",
      `export type Params = ${paramsType}${STATEMENT_TERMINATOR}`,
      `export type RouteContract = ProcedureRouteContract<${createStringLiteral(pathname)}, Params>${STATEMENT_TERMINATOR}`,
      "",
      "export const routeContract = {",
      `  pathname: ${createStringLiteral(pathname)},`,
      "  params: {} as Params,",
      "} as RouteContract;",
    ].join(NEWLINE);

    return {
      paramsType: params,
      dirPath,
    };
  });

  return {
    pathStructure: `${keyTypesImportStr}${NEWLINE}${importsStr}${NEWLINE}${NEWLINE}${pathStructureType}`,
    paramsTypes: dirParamsTypes,
  };
};
