import { createImportAlias } from "./alias.js";
import {
  NEWLINE,
  RPC4NEXT_GENERATED_SCHEMA_VERSION,
  RPC4NEXT_CLIENT_IMPORT_PATH,
  STATEMENT_TERMINATOR,
  TYPE_KEYS,
  TYPE_RPC_GENERATED_PATH_STRUCTURE,
} from "./constants.js";
import { createRelativeImportPath } from "./path-utils.js";
import { scanAppDir } from "./route-scanner.js";
import type { RouteManifest } from "./route-scanner.js";
import { createImport, createStringLiteral, createValueImport } from "./type-utils.js";

export const ROUTE_CONTRACT_GENERATED_MARKER =
  "// Generated by rpc4next-cli. Do not edit manually.";

type GeneratedParamsType = {
  dirPath: string;
  paramsType: string;
};

type GeneratedPathStructure = {
  paramsTypes: GeneratedParamsType[];
  pathStructure: string;
  routeManifests?: readonly RouteManifest[];
};

export const generateTestRouteManifest = (
  outputPath: string,
  routeManifests: readonly RouteManifest[],
) => {
  const imports = routeManifests.flatMap(({ fullPath, methods }) => {
    const importPath = createRelativeImportPath(outputPath, fullPath);

    return methods.map((method) =>
      createValueImport(method, importPath, createImportAlias(`${importPath}:${method}`, "Route")),
    );
  });
  const routes = routeManifests.map(({ fullPath, methods, pathname }) => {
    const importPath = createRelativeImportPath(outputPath, fullPath);
    const handlers = methods
      .map(
        (method) =>
          `    ${method}: ${createImportAlias(`${importPath}:${method}`, "Route")} as unknown as RpcTestRoute[${createStringLiteral(method)}],`,
      )
      .join(NEWLINE);

    return ["  {", `    pathname: ${createStringLiteral(pathname)},`, handlers, "  },"].join(
      NEWLINE,
    );
  });

  return [
    ROUTE_CONTRACT_GENERATED_MARKER,
    "",
    'import type { RpcTestRoute } from "rpc4next/client/test";',
    imports.length > 0 ? imports.join(NEWLINE) : "",
    "",
    "export const testRoutes = [",
    routes.join(NEWLINE),
    "] as const satisfies readonly RpcTestRoute[];",
  ].join(NEWLINE);
};

export const generatePathStructure = (
  outputPath: string,
  baseDir: string,
): GeneratedPathStructure => {
  const {
    pathStructure,
    imports,
    paramsTypes,
    routeManifests = [],
  } = scanAppDir(outputPath, baseDir);
  const pathStructureType = `export type PathStructure = ${TYPE_RPC_GENERATED_PATH_STRUCTURE}<${pathStructure || "{}"}, ${RPC4NEXT_GENERATED_SCHEMA_VERSION}>${STATEMENT_TERMINATOR}`;

  const importsStr = imports.length
    ? `${imports
        .sort((a, b) => a.path.localeCompare(b.path, undefined, { numeric: true }))
        .map((v) => v.statement)
        .join(NEWLINE)}`
    : "";

  const keyTypes = [
    TYPE_RPC_GENERATED_PATH_STRUCTURE,
    ...TYPE_KEYS.filter((type) => pathStructure.includes(type)),
  ];
  const keyTypesImportStr = createImport(keyTypes.join(" ,"), RPC4NEXT_CLIENT_IMPORT_PATH);
  const dirParamsTypes = paramsTypes.map(({ paramsType, dirPath, pathname }) => {
    const params = [
      ROUTE_CONTRACT_GENERATED_MARKER,
      "",
      'import type { ProcedureRouteContract } from "rpc4next/server";',
      "",
      `export type Params = ${paramsType}${STATEMENT_TERMINATOR}`,
      `export type RouteContract = ProcedureRouteContract<${createStringLiteral(pathname)}, Params>${STATEMENT_TERMINATOR}`,
      "",
      "export const routeContract = {",
      `  pathname: ${createStringLiteral(pathname)},`,
      "  params: {} as Params,",
      "} as RouteContract;",
    ].join(NEWLINE);

    return {
      paramsType: params,
      dirPath,
    };
  });

  return {
    pathStructure: `${keyTypesImportStr}${NEWLINE}${importsStr}${NEWLINE}${NEWLINE}${pathStructureType}`,
    paramsTypes: dirParamsTypes,
    routeManifests,
  };
};
