// Generated by rpc4next-cli. Do not edit manually.

import type { ProcedureRouteContract } from "rpc4next/server";

export type Params = {};
export type RouteContract = ProcedureRouteContract<"/patterns/parallel", Params>;

export const routeContract = {
  pathname: "/patterns/parallel",
  params: {} as Params,
} as RouteContract;