import { build } from "esbuild";
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

type PackedPackage = {
  filename: string;
  id: string;
  name: string;
};

const repoRoot = process.cwd();
const npmCommand = process.platform === "win32" ? "npm.cmd" : "npm";
const nodeCommand = process.platform === "win32" ? "node.exe" : "node";

const run = (command: string, args: string[], cwd: string, env?: NodeJS.ProcessEnv) =>
  execFileSync(command, args, {
    cwd,
    encoding: "utf8",
    env: {
      ...process.env,
      ...env,
    },
    stdio: ["ignore", "pipe", "pipe"],
  });

const readJson = <T>(filePath: string): T => JSON.parse(fs.readFileSync(filePath, "utf8"));

const assertExists = (filePath: string) => {
  if (!fs.existsSync(filePath)) {
    throw new Error(`Expected file to exist: ${filePath}`);
  }
};

const packPackage = (packageDir: string, destination: string): PackedPackage => {
  const output = run(npmCommand, ["pack", "--json", "--pack-destination", destination], packageDir);
  const [packed] = JSON.parse(output) as PackedPackage[];

  if (!packed) {
    throw new Error(`npm pack did not report a package for ${packageDir}`);
  }

  assertExists(path.join(destination, packed.filename));

  return packed;
};

const extractPackage = (tarballPath: string, destination: string) => {
  fs.mkdirSync(destination, { recursive: true });
  run("tar", ["-xzf", tarballPath, "-C", destination], repoRoot);

  return path.join(destination, "package");
};

const installExtractedPackage = (
  nodeModulesDir: string,
  packageName: string,
  extractedPackageDir: string,
) => {
  const destination = path.join(nodeModulesDir, packageName);
  fs.mkdirSync(path.dirname(destination), { recursive: true });
  fs.cpSync(extractedPackageDir, destination, { recursive: true });

  return destination;
};

const installRootDependency = (nodeModulesDir: string, packageName: string) => {
  const source = path.join(repoRoot, "node_modules", packageName);
  const destination = path.join(nodeModulesDir, packageName);

  assertExists(source);
  fs.mkdirSync(path.dirname(destination), { recursive: true });
  fs.cpSync(source, destination, { recursive: true });
};

const runBundlerSmoke = async (cwd: string) => {
  const entryPath = path.join(cwd, "bundle-entry.ts");
  const outputPath = path.join(cwd, "bundle-output.js");

  fs.writeFileSync(
    entryPath,
    [
      'import { createRpcClient } from "rpc4next/client";',
      'import { nextRoute, procedure } from "rpc4next/server";',
      'import { HTTP_METHODS } from "rpc4next-shared";',
      "",
      'if (typeof createRpcClient !== "function") throw new Error("missing client export");',
      'if (typeof nextRoute !== "function") throw new Error("missing server export");',
      'if (typeof procedure !== "object") throw new Error("missing procedure export");',
      'if (!Array.isArray(HTTP_METHODS)) throw new Error("missing shared export");',
      "",
    ].join("\n"),
    "utf8",
  );

  await build({
    absWorkingDir: cwd,
    bundle: true,
    entryPoints: [entryPath],
    external: ["next/headers", "next/navigation", "next/server"],
    format: "esm",
    logLevel: "silent",
    outfile: outputPath,
    platform: "browser",
  });

  assertExists(outputPath);
};

const runCliSmoke = (cwd: string, cliPackageDir: string) => {
  const appDir = path.join(cwd, "app", "api", "hello");
  const outputDir = path.join(cwd, "src", "generated");
  fs.mkdirSync(appDir, { recursive: true });
  fs.mkdirSync(outputDir, { recursive: true });

  fs.writeFileSync(
    path.join(appDir, "route.ts"),
    ["export async function GET() {", "  return Response.json({ ok: true });", "}", ""].join("\n"),
    "utf8",
  );
  fs.writeFileSync(
    path.join(cwd, "rpc4next.config.json"),
    `${JSON.stringify(
      {
        baseDir: "app",
        outputPath: "src/generated/rpc.ts",
        paramsFile: "route-contract.ts",
      },
      null,
      2,
    )}\n`,
    "utf8",
  );

  run(nodeCommand, [path.join(cliPackageDir, "dist", "index.js")], cwd);

  const generatedPath = path.join(outputDir, "rpc.ts");
  const routeContractPath = path.join(appDir, "route-contract.ts");
  const generated = fs.readFileSync(generatedPath, "utf8");
  const routeContract = fs.readFileSync(routeContractPath, "utf8");

  if (!generated.includes('"$get"') || !generated.includes("export type PathStructure")) {
    throw new Error("Generated PathStructure did not include the GET route");
  }
  if (!routeContract.includes("Generated by rpc4next-cli")) {
    throw new Error("CLI did not generate the route contract marker");
  }
};

const main = async () => {
  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "rpc4next-package-smoke-"));

  try {
    const packDir = path.join(tmpDir, "packs");
    const extractDir = path.join(tmpDir, "extract");
    const fixtureDir = path.join(tmpDir, "fixture");
    const nodeModulesDir = path.join(fixtureDir, "node_modules");
    fs.mkdirSync(packDir, { recursive: true });
    fs.mkdirSync(fixtureDir, { recursive: true });
    fs.mkdirSync(nodeModulesDir, { recursive: true });

    const packageDirs = [
      path.join(repoRoot, "packages", "rpc4next-shared"),
      path.join(repoRoot, "packages", "rpc4next"),
      path.join(repoRoot, "packages", "rpc4next-cli"),
    ];

    const packedPackages = packageDirs.map((packageDir) => packPackage(packageDir, packDir));
    const installedPackageDirs = new Map<string, string>();

    for (const packedPackage of packedPackages) {
      const extractedPackageDir = extractPackage(
        path.join(packDir, packedPackage.filename),
        path.join(extractDir, packedPackage.name),
      );
      const packageJson = readJson<{ bin?: Record<string, string>; files?: string[] }>(
        path.join(extractedPackageDir, "package.json"),
      );

      assertExists(path.join(extractedPackageDir, "dist"));
      if (packedPackage.name === "rpc4next-cli") {
        assertExists(path.join(extractedPackageDir, packageJson.bin?.rpc4next ?? ""));
      }

      installedPackageDirs.set(
        packedPackage.name,
        installExtractedPackage(nodeModulesDir, packedPackage.name, extractedPackageDir),
      );
    }

    installRootDependency(nodeModulesDir, "chokidar");
    installRootDependency(nodeModulesDir, "readdirp");
    installRootDependency(nodeModulesDir, "server-only");

    await runBundlerSmoke(fixtureDir);
    runCliSmoke(fixtureDir, installedPackageDirs.get("rpc4next-cli") ?? "");

    console.log("[package-smoke-test] packed package bundling and CLI passed");
  } finally {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  }
};

await main();
