// Generated by rpc4next-cli. Do not edit manually.

import type { ProcedureRouteContract } from "rpc4next/server";

export type Params = { "parts": string[] };
export type RouteContract = ProcedureRouteContract<"/patterns/catch-all/[...parts]", Params>;

export const routeContract = {
  pathname: "/patterns/catch-all/[...parts]",
  params: {} as Params,
} as RouteContract;