// Generated by rpc4next-cli. Do not edit manually.

import type { ProcedureRouteContract } from "rpc4next/server";

export type Params = {};
export type RouteContract = ProcedureRouteContract<"/patterns/%E3%81%ZZ", Params>;

export const routeContract = {
  pathname: "/patterns/%E3%81%ZZ",
  params: {} as Params,
} as RouteContract;