name: Bun test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        next-version: ["14.0.0", "15.0.0", "from-package"]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install base dependencies
        run: bun install

      - name: Install target Next.js version
        run: |
          if [ "${{ matrix.next-version }}" = "from-package" ]; then
            echo "Using next from package.json"
          else
            echo "Installing next@${{ matrix.next-version }}"
            bun add "next@${{ matrix.next-version }}"
          fi

      - name: Print versions
        run: |
          bun -v
          bunx next --version

      - name: Lint
        run: bun run lint

      - name: Build
        run: bun run build:bun

      - name: Test
        run: bun run test
