name: GHA static checks

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gha-static-check:
    name: GHA static checks status check
    uses: watanabe-1/github-actions-common/.github/workflows/gha-static-check.yml@c24a1f966b3d2d20ca30379e5a27ed137bfe760f # v1.0.2
    permissions:
      contents: read
      checks: write
      pull-requests: write
      actions: read
    with:
      actionlint-self-action-path: "$/.github/actions/setup-toolchain"
