name: Auto Approve
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

permissions: {}

jobs:
  approve:
    name: Auto approve owner PR
    if: github.event.pull_request.user.login == github.repository_owner && ! github.event.pull_request.draft
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    permissions:
      pull-requests: write # required to submit PR approval review
    steps:
      - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              event: "APPROVE",
            });
