name: Label PRs

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

permissions: {}

jobs:
  label:
    name: Label pull request
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    permissions:
      contents: read # needed for actions/checkout
      pull-requests: write # needed for actions/labeler to apply labels
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6.0.1
