name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Setup Git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Extract version from tag
        id: extract_version
        run: |
          echo "version=${GITHUB_REF#refs/tags/v}" >> "$GITHUB_OUTPUT"

      - name: Get branch name
        id: get_branch
        run: |
          BRANCH=$(git branch -r --contains $GITHUB_SHA | grep -Eo 'origin/[^ ]+' | head -n1 | sed 's|origin/||')
          echo "branch=$BRANCH" >> "$GITHUB_OUTPUT"

      - name: Checkout the branch
        run: git checkout ${{ steps.get_branch.outputs.branch }}

      - name: Update package.json version
        run: |
          npm version ${{ steps.extract_version.outputs.version }} --no-git-tag-version

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Commit and Push updated version
        run: |
          git add package.json package-lock.json
          git commit -m "chore: bump version to v${{ steps.extract_version.outputs.version }}" || echo "No changes to commit"
          git push origin ${{ steps.get_branch.outputs.branch }}

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
