name: Report Coverage

on:
  workflow_run:
    workflows: ["Node test"]
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      pull-requests: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          name: coverage
          path: coverage
      - name: "Report Coverage"
        uses: davelosert/vitest-coverage-report-action@2500dafcee7dd64f85ab689c0b83798a8359770e # v2.9.3
        with:
          comment-on: pr,commit
